version: "3"
services:

  frontend:
    build:
      context: ./frontend
      args:
        - NODEJS_VERSION=${NODEJS_VERSION}
    ports:
      - ${FRONTEND_PORT}:80
    volumes:
      - ${SRC_PATH}:/var/www
      - ./logs/apache:/var/log/apache2
    working_dir: /var/www

  backend:
    build:
      context: ./backend
      args:
        - XDEBUG_PORT=${XDEBUG_PORT}
    ports:
      - ${BACKEND_PORT}:80
    volumes:
      - ${SRC_PATH}:/var/www
      - ./logs/php:/var/log/php
      - ./logs/apache:/var/log/apache2
    working_dir: /var/www
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_READ_HOST=db
      - DB_PORT=3306
      - DB_READ_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - FRAMEWORK_DIR_NAME=${FRAMEWORK_DIR_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=null
      - MAIL_PORT=1025

  db:
    build:
      context: ./mysql
      args:
        - MYSQL_DATABASE=${DB_NAME}
        - MYSQL_USER=${DB_USER}
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    ports:
      - ${DB_PORT}:3306

  redis:
    image: redis:6.2-alpine
    ports:
      - ${REDIS_PORT}:6379

volumes:
  db-store:
